FEATURE_VARS = [
    "DUEXTTAU", "DUSCATAU", "DUANGSTR",
    "QV2M", "PS", "SLP", "WSPD10", "WDIR10", "T2M_C",
    "HOUR_SIN", "HOUR_COS", "DOY_SIN", "DOY_COS",
    "DUST_FINE_FRAC",
    "LOG1P_DUCMASS", "LOG1P_DUCMASS25", "LOG1P_DUSMASS", "LOG1P_DUSMASS25",
]